spring:
  cloud:
    gateway:
      routes:
        - id: get-token
          uri: http://localhost:8081
          predicates:
            - Path=/auth/token/issue
          filters:
            - RewritePath=/auth/token/issue?(?<segment>/*), /auth/token/issue
        - id: health-app
          uri: http://localhost:8083
          predicates:
            - Path=/health/**
          filters:
            - RemoveRequestHeader=X-user-id
            - RequiredHeaderCheck
            - Authorization
            - RewritePath=/health/?(?<segment>/*), /$\{segment}

auth:
  url: http://localhost:8081
  path:
    token-verify: /auth/token/verify


health:
  url: http://localhost:8083