server:
  port: 8081

keycloak:
  base-url: "http://localhost:9090/auth/realms/master/protocol/openid-connect"
  path:
    token: "/token"
    certs: "/certs"
  scope: health_app_scope
  client-id: health_app

